---
title: "Complete Setup"
author: "Edward Palmer"
date: "17/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vocabularies

1	CDM 5	SNOMED	Systematic Nomenclature of Medicine - Clinical Terms (IHTSDO)
2	CDM 5	ICD9CM	International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 1 and 2 (NCHS)
6	CDM 5	LOINC	Logical Observation Identifiers Names and Codes (Regenstrief Institute)
8	CDM 5	RxNorm	RxNorm (NLM)
12	CDM 5	Gender	OMOP Gender
13	CDM 5	Race	Race and Ethnicity Code Set (USBC)
17	CDM 5	Read	NHS UK Read Codes Version 2 (HSCIC)
34	CDM 5	ICD10	International Classification of Diseases, Tenth Revision (WHO)
44	CDM 5	Ethnicity	OMOP Ethnicity
55	CDM 5	OPCS4	OPCS Classification of Interventions and Procedures version 4 (NHS)
57	CDM 5	HES Specialty	Hospital Episode Statistics Specialty (NHS)
75	CDM 5	dm+d	Dictionary of Medicines and Devices (NHS)
82	CDM 5	RxNorm Extension	RxNorm Extension (OMOP)
87	CDM 5	Specimen Type	OMOP Specimen Type
111	CDM 5	Episode Type	OMOP Episode Type
115	CDM 5	Provider	OMOP Provider
116	CDM 5	Supplier	OMOP Supplier


